#!/bin/bash

IMAGE_NAME="macinbox-vsphere-10.15"
MACINBOX=/usr/local/bin/macinbox

if [[ ! -e ./vsphere-environment-do-not-add ]]
then
  echo "Please add a vsphere-environment-do-not-add file to set up the environment variables required to deploy"
  echo "These vary based on the target VMWare server. The list can be found at the bottom of the packer template."
  return 1
fi
source ./vsphere-environment-do-not-add

if [ ! -x $MACINBOX ]
then
    echo "This script requires that the macinbox gem be installed as root"
    exit 1
fi

if [ $USER != "root" ]
then
    echo "Please run this script with sudo --preserve-env=VAGRANT_HOME ./build-base-macosx-image"
    exit 1
fi

$MACINBOX \
    --verbose \
    --debug \
    --name $IMAGE_NAME \
    --disk 400 \
    --memory 4096 \
    --cpu 4 \
    --no-hidpi \
    --no-fullscreen \
    --password "$VAGRANT_USER_FINAL_PASSWORD"
    # End of macinbox options
