#!/bin/bash

IMAGE_NAME="macinbox-vagrant-10.15"
MACINBOX=/usr/local/bin/macinbox

if [ ! -x $MACINBOX ]
then
    echo "This script requires that the macinbox gem be installed as root"
    exit 1
fi

if [ $USER != "root" ]
then
    echo "Please run this script with sudo --preserve-env=VAGRANT_HOME ./build-base-macosx-image"
    exit 1
fi

$MACINBOX \
    --verbose \
    --debug \
    --name $IMAGE_NAME \
    --disk 400 \
    --memory 4096 \
    --vmware /Applications/VMware\ Fusion.app \
    --cpu 4 \
    --no-hidpi \
    --no-fullscreen \
    # End of macinbox options
